# here we are are doing following things.
# 1. telling travis to create docker service in running mode.
# 2. Creating image.
# 3. Running test suite.

# super user permission required to execute this build.
sudo: required

# We need a copy to docker in running mode.
services:
  - docker

# Set of commands that run before our test runs or before deploy our project.
# here tag name is used because we want to use generated docker image name  
before_install:
  - docker build -t 888mohitkumar/docker-react -f Dockerfile.dev .
  
# here we are running nmp run test to execute the test case in runing container. we are overriding the default command here.
# -- --coverage is used becase npm run test does not exists from dokcer contailer. so here it will make it exit. 

script:
  - docker run -e CI=true 888mohitkumar/docker-react ls
  
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker" #app name given during creating elasticbeanstalk in aws.
  env: "Docker-env" #name of env define here.
  bucket_name: "elasticbeanstalk-ap-south-1-139372003506"
  bucket_path: "docker" # this same as application name and will be created automatically 
  on:
    branch: main # on branch main when code merges then only deploy. Not on feature branch code push
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  