FROM node:16-alpine

WORKDIR '/app'

#This copy is used because package.json have dependency list and after that we run npm install so that we can down load that dependency.
COPY package.json .


#RUN npm install
RUN npm install react-scripts --save

RUN which npm

#[eslint] EACCES: permission denied, mkdir '/app/node_modules/.cache'
#ERROR in [eslint] EACCES: permission denied, mkdir '/app/node_modules/.cache'
# Due to above error below line was added . ABove error during running>  docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app 6c45758f5ccc
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

RUN chmod +x node_modules/.bin/react-scripts

RUN chmod -R 777 /usr/local/bin/npm

# this is use to copy the source code from curret working dir to /app folder
COPY . .

CMD ["npm","run","start"]